version: "3.7"

networks:
  rent_house_net:


volumes:
  mysql_data:
  phpmyadmin_data:


services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: rent_house
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql/
    networks:
      - rent_house_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmin_data:/var/www/html/
    networks:
      - rent_house_net
    ports:
      - 8080:80
    depends_on:
      - mysql
  # nginx:
  #   image: nginx:1.17.4-alpine
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - phpmyadmin_data:/var/www/html/:ro
  #   ports:
  #     - "90:80"
  #   networks:
  #     - rent_house_net
  #   depends_on:
  #     - mysql
  #     - phpmyadmin
